spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.url}
    username: ${mysql.user}
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 200
        format_sql: true
        show_sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      url: redis://${redis.password}@${redis.url}:${port}
      password: ${redis.password}

nhn:
  email: ${nhn.email}
  url: ${nhn.url}
  secretKey: ${nhn.secretKey}

oauth:
  uri: ${oauth.uri}

